services:
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: lionweb_test
      POSTGRES_PASSWORD: lionweb
    ports:
      - '5432:5432'

  model-repository:
    build: docker/model-repository
    depends_on:
      - postgres
    ports:
      - '3005:3005'

  adminui:
    build:
      context: .
      dockerfile: docker/adminui/Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - postgres
      - model-repository
