name: Linting
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Use the maintained v4 action and a current Node LTS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'          # keep this in sync with local dev
          cache: 'npm'                # speeds up, safe for optional deps
      # Pin npm to a modern major (fixes optional-deps glitches seen in npm 9.x)
      - name: Upgrade npm
        run: npm i -g npm@^10
      - name: Setup
        run: npm run setup
      - name: Install
        run: npm install
      - name: Check
        run: npm run check
      - name: Lint Check
        run: npm run lint-check
